Repository saltudelft/type4py-vscode-ext, pull requests merged in 2021-07, with the labels that each got.

#10 Improve visibility of type check setting
  README.md
  package.json
Labels: documentation

#11 Update launch.json to only compile
  .vscode/launch.json
  package-lock.json
  package.json
  test/runTest.ts
Labels: bug

#12 Allow whitespace after annotation
  README.md
  src/completionProvider.ts
Labels: bug

#15 Automatic type inference when opening a new Python source file
  README.md
  package.json
  src/extension.ts
  src/settings.ts
Labels: enhancement

#16 Capture canceled type predictions by the user + submission
  src/completionProvider.ts
  src/extension.ts
  test/suite/providers/completionProvider.test.ts
Labels: enhancement

#18 Multi-variable in function support
  CHANGELOG.md
  README.md
  package.json
  python/sample_files/func_multi_var.py
  src/type4pyData.ts
Labels: bug
